name: Eleventy Build
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build_deploy:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 21

      - name: Install & build
        run: |
          npm i
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site
          publish_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
